stages:
  - staging

deploy_job:
  stage: staging
  tags: 
    - staging
  script:
    - echo "Running from CI build directory"
    - git config --global --add safe.directory /opt/apps/train
    - cd /opt/apps/train
    - git reset --hard
    - git pull origin staging
    - npx mix
    - npm run dev
    - php artisan migrate
    - php artisan optimize
    - php artisan config:clear
    - php artisan db:seed --class=RoleSeeder
    - php artisan db:seed --class=PermissionSeeder
  
  after_script:
    - echo "Cleaning up temporary files..."
  only:
    - staging
