stages:
  - deploy

deploy_job:
  stage: deploy
  tags: 
    - deploy
  script:
    - "cd /opt/apps/train"
    - "git reset --hard"  
    - "git pull --force origin staging" 
    - "npm run dev" 
    - "php artisan migrate"
    - "php artisan optimize"
    - "php artisan config:clear"
  after_script:
    - echo "Cleaning up temporary files..." 
  only:
    - staging
    