stages:
  - staging

deploy_job:
  stage: staging
  tags: 
    - staging
  script:
    - echo "Running from CI build directory"
    - git config --global --add safe.directory /opt/apps/train
    - cd /opt/apps/train
    - git reset --hard
    - git pull origin staging
    #- npm run dev
    - echo "Successfully pulled latest changes"
<<<<<<< HEAD
    - npm install
    - npx mix
    - php artisan optimize
    - php artisan config:clear
<<<<<<< HEAD
=======
=======
    #- npm run dev
>>>>>>> ccaad04 (Update .gitlab-ci.yml file)
>>>>>>> staging
  after_script:
    - echo "Cleaning up temporary files..."
  only:
    - staging