stages:
  - build

deploy_job:
  stage: build
  tags: 
    - staging
  script:
    - git config --global --add safe.directory /opt/apps/train
    - "git reset --hard"  
    - "git pull --force origin staging" 
    - "composer install"
    - "npm run dev" 
    - "php artisan migrate"
    - "php artisan optimize"
    - "php artisan config:clear"
  after_script:
    - echo "Cleaning up temporary files..." 
  only:
    - staging
    