stages:
  - staging

deploy_job:
  stage: staging
  tags: 
    - staging
  script:
    - echo "Running from CI build directory"
    - git config --global --add safe.directory /opt/apps/train
    - cd /opt/apps/train
    - git reset --hard
    - git pull origin staging
    - npx mix
    - npm run dev
    
    - composer require owen-it/laravel-auditing:"^13.0"
    - php artisan vendor:publish --provider "OwenIt\Auditing\AuditingServiceProvider" --tag="config"
    - php artisan vendor:publish --provider "OwenIt\Auditing\AuditingServiceProvider" --tag="migrations"
    - php artisan migrate
    
    # Clear caches and optimize
    - php artisan optimize
    - php artisan route:clear
    - php artisan config:clear
  
  after_script:
    - echo "Cleaning up temporary files..."
  only:
    - staging
